extends: eslint:recommended

env: 
  es6: true
  node: true
  
parserOptions:
  ecmaVersion: 2018
  sourceType: node

rules:
  quotes:
    - warn
    - single
  eqeqeq: warn
  no-var: warn
  prefer-const:
    - warn
    - destructuring: all
  indent:
    - off
    - 2
    - SwitchCase: 1
  no-console: off
